<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformCaptureOutput>false</TestingPlatformCaptureOutput>
    <IsTestProject>true</IsTestProject>
    <UseTestingPlatformProtocol>true</UseTestingPlatformProtocol>
    <IsTestingPlatformEnabled>true</IsTestingPlatformEnabled>
    <NoWarn>$(NoWarn);CA2000;CA2201;CS8604;CS8892</NoWarn>
  </PropertyGroup>

  <ItemGroup Label="Using Directives">
    <Using Include="TUnit.Core" />
    <Using Include="TUnit.Assertions" />
    <Using Include="TUnit.Assertions.Extensions" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Moq" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\src\Tsabo.Data.Schema.Sqlite\Tsabo.Data.Schema.Sqlite.csproj" />
  </ItemGroup>
</Project>
