<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Database Providers">
    <!-- EF Core -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <!-- PostgreSQL -->
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <!-- SQLite -->
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <!-- SQL Server -->
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup Label="Versioning">
    <PackageVersion Include="MinVer" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageVersion Include="TUnit" Version="1.47.0" />
  </ItemGroup>
</Project>